//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class APROBADOS
    {
        public int APROBADO_ID { get; set; }
        public int SOLICITUD_ID { get; set; }
        public System.DateTime APROBADO_FECHA { get; set; }
        public string APROBADO_RESPONSABLE { get; set; }
        public string APROBADO_OBSERVACIONES { get; set; }
    
        public virtual SOLICITUDES SOLICITUDES { get; set; }
    }
}
