//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATOS()
        {
            this.INSTALACIONES = new HashSet<INSTALACIONES>();
            this.MANTENIMIENTOS = new HashSet<MANTENIMIENTOS>();
        }
    
        public int CONTRATO_ID { get; set; }
        public int COMPRA_ID { get; set; }
        public string CONTRATO_NUMERO { get; set; }
        public System.DateTime CONTRATO_FECHA { get; set; }
        public string CONTRATO_RESP_UACI { get; set; }
        public string CONTRATO_RESP_PROVEEDOR { get; set; }
        public string CONTRATO_RESP_DEPTO { get; set; }
        public string CONTRATO_OBSERVACION { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTALACIONES> INSTALACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTENIMIENTOS> MANTENIMIENTOS { get; set; }
    }
}
