//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD
    {
        public int DET_SOLICITUD_ID { get; set; }
        public int PROD_INSTITUCION_ID { get; set; }
        public int SOLICITUD_ID { get; set; }
        public int DET_SOLICITUD_CANTIDAD { get; set; }
        public string DET_SOLICITUD_DESCRIPCION { get; set; }
    
        public virtual SOLICITUDES SOLICITUDES { get; set; }
        public virtual PRODUCTOS_INSTITUCION PRODUCTOS_INSTITUCION { get; set; }
    }
}
