//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_MANTENIMIENTO
    {
        public int DET_MANTO_ID { get; set; }
        public int MANTO_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public string DET_MANTO_ESTADO_INICIAL { get; set; }
        public string DET_MANTO_ESTADO_FINAL { get; set; }
        public string DET_MANTO_DESCRIPCION { get; set; }
    
        public virtual MANTENIMIENTOS MANTENIMIENTOS { get; set; }
        public virtual EQUIPOS EQUIPOS { get; set; }
    }
}
