//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_INSTALACION
    {
        public int DET_INSTALACION_ID { get; set; }
        public int INSTALACION_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public string DET_INSTALACION_ESTADO_INICIAL { get; set; }
        public string DET_INSTALACION_ESTADO_FINAL { get; set; }
        public string DET_INSTALACION_DESCRIPCION { get; set; }
        public string DET_INSTALACION_AUTORIZADO_POR { get; set; }
    
        public virtual INSTALACIONES INSTALACIONES { get; set; }
        public virtual EQUIPOS EQUIPOS { get; set; }
    }
}
