//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS
    {
        public int DOCU_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public string DOCU_NOMBRE { get; set; }
        public string DOCU_URL { get; set; }
    
        public virtual EQUIPOS EQUIPOS { get; set; }
    }
}
