//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTALACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTALACIONES()
        {
            this.DETALLE_INSTALACION = new HashSet<DETALLE_INSTALACION>();
        }
    
        public int INSTALACION_ID { get; set; }
        public int CONTRATO_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public System.DateTime INSTALACION_INICIO { get; set; }
        public System.DateTime INSTALACION_FINALIZACION { get; set; }
        public string INSTALACION_RESPONSABLE { get; set; }
        public string INSTALACION_DESCRIPCION { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_INSTALACION> DETALLE_INSTALACION { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
