//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTITUCIONES()
        {
            this.COMPRAS = new HashSet<COMPRAS>();
            this.DEPARTAMENTOS_INSTITUCION = new HashSet<DEPARTAMENTOS_INSTITUCION>();
            this.PRODUCTOS_INSTITUCION = new HashSet<PRODUCTOS_INSTITUCION>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.PROVEEDORES = new HashSet<PROVEEDORES>();
        }
    
        public int INSTITUCION_ID { get; set; }
        public int MUNICIPIO_ID { get; set; }
        public string INSTITUCION_NOMBRE { get; set; }
        public string INSTITUCION_ENCARGADO { get; set; }
        public string INSTITUCION_TELEFONO { get; set; }
        public string INSTITUCION_DIRECCION { get; set; }
        public string INSTITUCION_DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTOS_INSTITUCION> DEPARTAMENTOS_INSTITUCION { get; set; }
        public virtual MUNICIPIOS MUNICIPIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOS_INSTITUCION> PRODUCTOS_INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDORES> PROVEEDORES { get; set; }
    }
}
