//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICITACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICITACIONES()
        {
            this.OFERTAS = new HashSet<OFERTAS>();
        }
    
        public int LICITACION_ID { get; set; }
        public int SOLICITUD_ID { get; set; }
        public int LICITACION_NUMERO { get; set; }
        public int LICITACION_ANIO { get; set; }
        public System.DateTime LICITACION_INICIO { get; set; }
        public System.DateTime LICITACION_FINALIZACION { get; set; }
        public string LICITACION_DESCRIPCION { get; set; }
    
        public virtual SOLICITUDES SOLICITUDES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFERTAS> OFERTAS { get; set; }
    }
}
