//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANTENIMIENTOS()
        {
            this.DETALLE_MANTENIMIENTO = new HashSet<DETALLE_MANTENIMIENTO>();
        }
    
        public int MANTO_ID { get; set; }
        public int TIPO_MANTO_ID { get; set; }
        public int CONTRATO_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public System.DateTime MANTO_INICIO { get; set; }
        public System.DateTime MANTO_FINALIZACION { get; set; }
        public string MANTO_RESPONSABLE { get; set; }
        public string MANTO_DESCRIPCION { get; set; }
        public string MANTO_AUTORIZADO_POR { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_MANTENIMIENTO> DETALLE_MANTENIMIENTO { get; set; }
        public virtual TIPO_MANTENIMIENTOS TIPO_MANTENIMIENTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
