//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTAS
    {
        public int OFERTA_ID { get; set; }
        public int LICITACION_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public float OFERTA_PRECIO { get; set; }
        public string OFERTA_DESCRIPCION { get; set; }
    
        public virtual LICITACIONES LICITACIONES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
