//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_PROVEEDOR
    {
        public int PROD_PROVEEDOR_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public string PROD_PROVEEDOR_NOMBRE { get; set; }
        public string PROD_PROVEEDOR_MARCA { get; set; }
        public string PROD_PROVEEDOR_MODELO { get; set; }
        public Nullable<int> PROD_PROVEEDOR_ANIO { get; set; }
        public Nullable<float> PROD_PROVEEDOR_BTU { get; set; }
        public Nullable<float> PROD_PROVEEDOR_POTENCIA { get; set; }
        public string PROD_PROVEEDOR_COLOR { get; set; }
        public Nullable<int> PROD_PROVEEDOR_EXISTENCIAS { get; set; }
        public string PROD_PROVEEDOR_DESCRIPCION { get; set; }
        public Nullable<float> PROD_PROVEEDOR_VOLTAJE { get; set; }
        public Nullable<float> PROD_PROVEEDOR_AREA { get; set; }
    
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
