//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUDES()
        {
            this.APROBADOS = new HashSet<APROBADOS>();
            this.DETALLE_SOLICITUD = new HashSet<DETALLE_SOLICITUD>();
            this.LICITACIONES = new HashSet<LICITACIONES>();
        }
    
        public int SOLICITUD_ID { get; set; }
        public int TIPO_SOLICITUD_ID { get; set; }
        public int DEPTO_INSTITUCION_ID { get; set; }
        public int SOLICITUD_CODIGO { get; set; }
        public string SOLICITUD_RESPONSABLE { get; set; }
        public Nullable<System.DateTime> SOLICITUD_FECHA { get; set; }
        public bool SOLICITUD_ESTADO { get; set; }
        public string SOLICITUD_OBSERVACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APROBADOS> APROBADOS { get; set; }
        public virtual DEPARTAMENTOS_INSTITUCION DEPARTAMENTOS_INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_SOLICITUD> DETALLE_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICITACIONES> LICITACIONES { get; set; }
        public virtual TIPO_SOLICITUDES TIPO_SOLICITUDES { get; set; }
    }
}
