//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MANTENIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_MANTENIMIENTOS()
        {
            this.MANTENIMIENTOS = new HashSet<MANTENIMIENTOS>();
        }
    
        public int TIPO_MANTO_ID { get; set; }
        public string TIPO_MANTO_NOMBRE { get; set; }
        public string TIPO_MANTO_DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTENIMIENTOS> MANTENIMIENTOS { get; set; }
    }
}
