//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOES
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string USUARIO_USUARIO { get; set; }
        public Nullable<int> PROVEEDOR_ID { get; set; }
        public Nullable<int> INSTITUCION_ID { get; set; }
        public int ROL_ID { get; set; }
        public string USUARIO_NOMBRE { get; set; }
        public string USUARIO_CORREO { get; set; }
        public string USUARIO_TELEFONO { get; set; }
        public string USUARIO_CONTRASENIA { get; set; }
        public bool USUARIO_ESTADO { get; set; }
        public bool USUARIO_BLOQUEADO { get; set; }
    
        public virtual INSTITUCIONES INSTITUCIONES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
